version: "3.7"
services:

 salbase:
    image: salbase:${IMAGE_TAG}
    build:
      context: ./salbase
      labels:
        com.description: "LSST DDS/SAL base docker image."

  salrpm:
    image: salrpm:${IMAGE_TAG}
    depends_on:
      - salbase
    build:
      context: ./salrpm
      labels:
        com.description: "Docker OpenSplice/SAL image rpms"
      args:
        salbase_image_tag : ${IMAGE_TAG}
        SAL_VERSION : "3.10.0_001-3.10.0.el7"
        OSPL_VERSION : "6.9.0"

  salsrc:
    image: salsrc:${IMAGE_TAG}
    depends_on:
      - salrpm
    build:
      context: ./salsrc
      labels:
        com.description: "Docker OpenSplice/SAL image from source"
      args:
        salrpm_image_tag : ${IMAGE_TAG}
        TS_SAL_VERSION : "v3.10.0"
        TS_XML_VERSION : "v3.10.0"
        INSTALL_PATH : "/opt/lsst"

  salobj:
    image: salobj:${IMAGE_TAG}
    depends_on:
      - salsrc
    build:
      context: ./salobj
      labels:
        com.description: "Docker inage for ts_salobj"
      args:
        salsrc_image_tag : ${IMAGE_TAG}
        TS_SALOBJ_VERSION : "v4.1.0"
        TS_IDL_VERSION: "v0.2.0"
        INSTALL_PATH : "/opt/lsst"
        GIT_LSST_TS: "https://github.com/lsst-ts"
        REPOS_TMP: "/tmp/repos"

  at_headerservice:
    image: at_headerservice:${IMAGE_TAG}
    depends_on:
      - salobj
    build:
      context: ./at_headerservice
      labels:
        com.description: "Docker image for at_headerservice"
      args:
        salobj_image_tag : ${IMAGE_TAG}
        HEADERSERVICE_VERSION : "0.9.8"
        SALPYTOOLS_VERSION: "0.9.7"
        FITSIO_VERSION : "1.0.4"
        HSUSER : "headerservice"
        INSTALL_PATH : "/opt/lsst"
        GIT_LSST_DM: "https://github.com/lsst-dm"
        REPOS_TMP: "/tmp/repos"
